sudo: enabled
os: osx
language: c

install:
  - git clone https://github.com/cc65/cc65 /tmp/cc65 &&
    make -C /tmp/cc65 ca65 ld65 &&
    /tmp/cc65/bin/ca65 --version

  - git clone https://github.com/mach-kernel/cadius /tmp/cadius &&
    make -C /tmp/cadius

script:
  - cd $TRAVIS_BUILD_DIR/desktop &&
    MAKE_FLAGS="CC65=/tmp/cc65/bin" res/go.sh

  - cd $TRAVIS_BUILD_DIR/desk.acc &&
    MAKE_FLAGS="CC65=/tmp/cc65/bin" res/go.sh &&
    CADIUS="/tmp/cadius/bin/release/cadius" res/package.sh
